parameters:
#    acme_mdm.example.class: Acme\MdmBundle\Example

services:
#    acme_mdm.example:
#        class: %acme_mdm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
